config/routes.rb
Rails.application.routes.draw do
  resources :leases do 
    member do
      put "approve", to: "leases#approve"
      put "disapprove", to: "leases#disapprove"
    end
  end

  resources :users, only: [:show, :edit, :update]
  resources :spaces do
    resources :leases
  end
  
  root to: 'pages#home'

#put 'users/:id' => 'users#update', :as => :id

  devise_for :users, :path => '', 
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up =>'signup'}

  get 'leases' => 'leases#index'
  get 'leases/:id' => 'leases#index'

  get 'listings' => 'pages#listings'
  get 'listings/search' => 'pages#listings'
  post 'listings/search' => 'pages#listings'

  get 'dashboard' => 'admin#dashboard'
  get 'dashboard/users' => 'admin#indexUsers'
  get 'dashboard/spaces' => 'admin#indexSpaces'

  get 'submission' => 'pages#submission'
  get 'spaces/new' => 'spaces#new'

  #get 'users/:id' => 'users#show'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/admin/makeAdmin' => 'admin#makeAdmin'
  post '/admin/makeAdmin' => 'admin#makeAdmin'

  get 'spaces/tagged/:tag', to: 'spaces#index', as: :tag



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/_header.html.erb
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Synergy Space</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Dashboard</a></li>
            <li>
              <a href="/users/<%= current_user.id %>">Profile</a>
            </li>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
          </ul>
        </div>
      </div>
    </nav>

    

app/views/admin/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="<%= 'active' if current_page?(dashboard_path) %>"><a href="/dashboard">Overview <span class="sr-only">(current)</span></a></li>
    <li class="<%= 'active' if current_page?(dashboard_users_path) %>"><a href="/dashboard/users">Users List</a></li>
    <li class="<%= 'active' if current_page?(dashboard_spaces_path) %>"><a href="/dashboard/spaces">Spaces List</a></li>
    <!-- <li><a href="#">Export</a></li>
  </ul> -->
  <!-- <ul class="nav nav-sidebar">
    <li><a href="">Analytics</a></li>
  </ul> -->

</div>

app/views/admin/dashboard.html.erb
<main class="dashboard">
	<%= render "admin/header" %>

    <div class="container-fluid">
      <div class="row page-start">
        <%= render 'admin/sidebar' %>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>
          <p id="open" style="display: none"><%= @openNum %></p>
          <p id="cubicle" style="display: none"><%= @cubicleNum %></p>
          <p id="team" style="display: none"><%= @teamNum %></p>
          <p id="combo" style="display: none"><%= @combinationNum %></p>
          <div id="chart_div"></div>
         
          <script type="text/javascript">

          $(function(){

            drawChart();
            

            // Callback that creates and populates a data table,
            // instantiates the pie chart, passes in the data and
            // draws it.
            function drawChart() {

              // Create the data table.
              var data = new google.visualization.DataTable();
              data.addColumn('string', 'Topping');
              data.addColumn('number', 'Slices');
              data.addRows([
                ['Open Concept', parseInt($("#open").text())],
                ['Cubicles', parseInt($("#cubicle").text())],
                ['Team', parseInt($("#team").text())],
                ['Combination', parseInt($("#combo").text())],
              ]);

              google.load('visualization', '1.0', {'packages':['corechart']});

              // Set a callback to run when the Google Visualization API is loaded.
              google.setOnLoadCallback(drawChart);

              // Set chart options
              var options = {'title':'System Status: Space Types Totals',
                             'width':800,
                             'height':600};



              // Instantiate and draw our chart, passing in some options.
              var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
              chart.draw(data, options);


            }
            
            
          });

          </script>
        </div>
      </div>
    </div>
</main>

app/views/admin/indexSpaces.html.erb
<main class="dashboard">
	<%= render "admin/header" %>

    <div class="container-fluid">
      <div class="row page-start">
        <%= render 'admin/sidebar' %>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h2 class="sub-header">Spaces</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Space ID</th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Price</th>
                  <th>Vacancies</th>
                  <th>Owner</th>
                  <th>Type</th>
                </tr>
              </thead>
              <tbody>
              	<% @spaces = Space.all %>
              	<% @spaces.each do |space| %>
              		<tr>
              			<td><%= space.id %></td>
              			<td><%= space.name %></td>
            	  		<td><%= space.streetnum %> 
                      <%= space.street %>, <%= space.city %>, <%= space.state %>
                    </td>
            	  		<td><%= space.price %></td>
            	  		<td><%= space.vacancies %></td>
            	  		<td><%= space.user.name %></td>
                    <td><%= space.spacetype %></td>
            	  	</tr>
              	<% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</main>

app/views/admin/indexUsers.html.erb
<main class="dashboard">
	<%= render "admin/header" %>

    <div class="container-fluid">
      <div class="row page-start">
        <%= render 'admin/sidebar' %>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h2 class="sub-header">Users</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>User #</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Occupation</th>
                  <th>Last used IP</th>
                  <th>Admin</th>
                  <th>Profile</th>
                </tr>
              </thead>
              <tbody id="userTable">
              	<% @users = User.all %>
              	<% @users.each do |user| %>
                
              		<tr id=<%= user.id %>>
              			<td><%= user.id %></a></td>
              			<td><%= user.name %></td>
            	  		<td><%= user.email %></td>
            	  		<td><%= user.occupation %></td>
            	  		<td><%= user.last_sign_in_ip %></td>
            	  		<td> <select id=<%= "adminSelect" + user.id.to_s %>>
                       <option class="admin1" value="admin1"><%= user.admin.to_s.capitalize %></option>
                        <option class="admin2" value="admin2"><%= (!user.admin).to_s.capitalize %></option>
                  </select>  </td>
                    <td><a href="/users/<%= user.id %>">View</a></td>
              	  	</tr>
              	<% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    
</main>