config/routes.rb
Rails.application.routes.draw do
  resources :leases do 
    member do
      put "approve", to: "leases#approve"
      put "disapprove", to: "leases#disapprove"
    end
  end

  resources :users, only: [:show, :edit, :update]
  resources :spaces do
    resources :leases
  end
  
  root to: 'pages#home'

#put 'users/:id' => 'users#update', :as => :id

  devise_for :users, :path => '', 
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up =>'signup'}

  get 'leases' => 'leases#index'
  get 'leases/:id' => 'leases#index'

  get 'listings' => 'pages#listings'
  get 'listings/search' => 'pages#listings'
  post 'listings/search' => 'pages#listings'

  get 'dashboard' => 'admin#dashboard'
  get 'dashboard/users' => 'admin#indexUsers'
  get 'dashboard/spaces' => 'admin#indexSpaces'

  get 'submission' => 'pages#submission'
  get 'spaces/new' => 'spaces#new'

  #get 'users/:id' => 'users#show'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/admin/makeAdmin' => 'admin#makeAdmin'
  post '/admin/makeAdmin' => 'admin#makeAdmin'

  get 'spaces/tagged/:tag', to: 'spaces#index', as: :tag



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/space.rb
class Space < ActiveRecord::Base

	has_attached_file :avatar
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"], :default_url => "/images/:style/missing.png"
	belongs_to :user
	has_many :leases
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, presence: true
	validates :spacetype, presence: true
	validates :streetnum, presence: true
	validates :street, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :price, presence: true
	validates :vacancies, presence: true
	validates :areacode, presence: true

  	ratyrate_rateable "reputation"

  	acts_as_taggable
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    if params[:tag]
      @spaces = Space.tagged_with(params[:tag])
    else
      @spaces = Space.where("vacancies > ?", 0)
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @leased = Lease.where(user: current_user, space: @space)
    if @leased.count > 0
      @coworker = true
    else
      @coworker = false
    end
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = current_user.spaces.build(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :spacetype, :streetnum, :street, :city, :state, :areacode, :price, :description, :vacancies, :avatar, :tag_list)
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for(@space, :html => { :multipart => true }) do |f| %>
	<div class="col-md-10">
		<div class="panel panel-default">
	        <div class="panel-heading" style="overflow:auto;">
	    		<h3 class="panel-title" style="float:left;">Space Action</h3>
	    	</div>
			<div class="panel-body">
				<img class="user-avatar" src="">
				<div class="label-container">
					<% if @space.errors.any? %>
						<div id="error_explanation">
						  <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

						  <ul>
						  <% @space.errors.full_messages.each do |message| %>
						    <li><%= message %></li>
						  <% end %>
						  </ul>
						</div>
					<% end %>

					
					Title: <%= f.text_field :name, :class => "form-control" %><br />
					Type: <%= f.select :spacetype, options_for_select(["Open Concept", "Cubicles", "Team", "Combination"]), :class => 'form-control' %><br /><br />
					Street Number: <%= f.text_field :streetnum, :class => "form-control" %><br />
					Street: <%= f.text_field :street, :class => "form-control" %><br />
					City: <%= f.select :city, options_for_select(["Toronto", "New York", "San Francisco"]), :class => 'form-control' %><br /><br />
					State/Province: <%= f.select :state, options_for_select(["Ontario", "New York", "California"]), :class => 'form-control' %><br /><br />
					Postal code: <%= f.text_field :areacode, :class => "form-control" %> <br />
					Vacancies: <%= f.text_field :vacancies, :class => "form-control" %><br />

					Price: <%= f.text_field :price, :class => "form-control" %><br />
					Description: <%= f.text_area :description , :rows => "10", :class => "form-control" %><br />

			  		Tags (revelant vibe): <br/>
			  		<%= f.text_field :tag_list, :class => "form-control" %>
					<br>avatar: <%= f.file_field :avatar %><br />

					<%= f.submit :submit , :class => "form-control" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/spaces/_listings.html.erb
<div class="search-wrapper">
  <div class="search-panel">

    <div class="form-group">
      <%= form_tag(listings_search_path) do %>

        <form class="form-inline search-form">
          <%= select_tag :city , 
            "<option>New York</option>
              <option>Toronto</option>
              <option>San Francisco</option>".html_safe, 
            class:"form-control formfield", style:"display:inline" %>

          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1" style="font-family:Courier New;">MIN $</span>
            <%= text_field_tag :min_price, (params[:min_price] or 1), class:"form-control", style:"" %>
          </div>

          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1" style="font-family:Courier New;">MAX $</span>
            <%= text_field_tag :max_price, (params[:max_price] or 99999), class:"form-control", style:""  %>
          </div>

          <%= submit_tag "Search", :disable_with => "Submitting...", class:"btn btn-block btn-default", style:"background: #E5E3E3" %>

        </form>

      <% end %>
    </div>
  </div>
</div>

<h1 class="cover-heading text-center heading-spacer">Space Listings</h1>
<hr></hr>
<div class="space-wrapper">

  <% if @spaces.count == 0 %>
    <p>Sorry, no.</p>
  <% else %>

    <% @spaces.each do |space| %>
    <div class="panel panel-default">
      <div class="panel-heading star-col">
        <div class="col-md-10"><h4 class="spacename"><%= link_to space.name, space %></h4></div>
        <div class="col-md-2">
          <p ><span><%= rating_for space, "reputation", :disable_after_rate => true, :cancel => false, :half_show => true %>
          </p>
        </div>
      </div>
      <div class="panel-body">
        <div class="photo-wrap col-md-6">
          <%= image_tag space.avatar.url , :class => "space-photo" %>
        </div>      
        <div class="Media-body col-md-6">
          
          <p class="address"><%= space.streetnum %> <%= space.street %>, <%= space.city %>, <%= space.state %></p>
          <p><span class="info">Type: </span><%= space.spacetype %></p>
          <p><span class="info">Price: </span><%= space.price %></p>
          <p><span class="info">Vacancies: </span><%= space.vacancies %></p>
          <p class="description"><%= space.description %></p>
          <p class="keywords">
            <span class="info">Synergy tags:</span>
              <% space.tag_list.each do |keyword| %>
                <a href="/spaces/tagged/<%= keyword %>">
                  <span class="keywordtag">
                    <%= keyword %>
                  </span>
                </a>
              <% end %>
          </p>
        </div>
      </div>
    </div>

    <% end %>

  <% end %>

  

  <script>

  $(function(){
    setTimeout(function(){
      $(".star > img").unbind('mouseout mouseover click hover');
      $(".star").css("cursor", "default");
    },500) 
  })
  
  </script>
  
</div>

app/views/spaces/edit.html.erb
<main class="page">
<div class="container col-md-offset-2 col-md-10">	
	<h1 class="space-action">Editing</h1>

	<%= render 'form' %>
</div>
	<%= link_to 'Show', @space %> |
	<%= link_to 'Back', spaces_path %>

</main>

app/views/spaces/index.html.erb
<%= render "spaces/listings" %>

app/views/spaces/new.html.erb
<main class="page">
	<div class="submit-page">
		<div class="container col-md-offset-3 col-md-9">	
			<h1 class="space-action">Creating </h1>
			<%= render 'form' %>
		</div>
	</div>

</main>

app/views/spaces/show.html.erb
<main class="page">
  <p id="notice"><%= notice %></p>

  <div class="space-info-wrapper autoflow">
    <div class="col-md-12">
      <div class="col-md-12">
        <div class="panel panel-default autoflow" >
          <div class="panel-heading margin-bottom">
              <h1 class="spacename space-title"><%= @space.name %> </h1>
              <%= @space.streetnum %> <%= @space.street %>,
              <%= @space.city %>, <%= @space.state %>, 
              <%= @space.areacode %>
          </div>
          <div class="col-md-6">
            <p>
              <strong>Type:</strong>
              <%= @space.spacetype %>
            </p>
            <p>
              <strong>Price:</strong>
              <%= @space.price %>
            </p>
            <p>
              <strong>Vacancies:</strong>
              <%= @space.vacancies %>
            </p>
            <p>
              <strong>Description:</strong>
              <%= @space.description.gsub(/\n/, '<br/>').html_safe %>
            </p>
            <p>
              <strong>Owner:</strong>
              <%= @space.user.name %>
            </p>
            <p>
              <strong>Rating:</strong>
              <%= rating_for @space, "reputation", :disable_after_rate => true, :cancel => false, :half_show => true %>
            </p>
            <p class="keywords">
              <span class="user-label"><strong>Synergy tags:</strong></span>
                <% @space.tag_list.each do |keyword| %>
                  <a href="/spaces/tagged/<%= keyword %>">
                    <span class="keywordtag">
                      <%= keyword %>
                    </span>
                  </a>
                <% end %>
            </p>
          </div>
          <div class="col-md-6">
            <%= image_tag @space.avatar.url, :class => "space-photo"%>
          </div>
        </div>
      </div>
      
    </div>

  </div>

  <% if current_user == @space.user %>
    <%= link_to 'Edit', edit_space_path(@space), class:"btn btn-default top-margin" %> 
    <%= link_to 'Destroy', @space, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default top-margin" %> 
  <% end%>

  <% if current_user != @space.user and @leased.count == 0%>

  <div class="apply-lease-wrapper autoflow">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Apply to lease</h1>
      <%= form_for([@space, @space.leases.build]) do |f| %>

        <div class="form-group">
            <%= f.label :Lease_start_date %><br>
            <%= f.datetime_select :startdate, :class=>"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Lease_end_date %><br>
          <%= f.datetime_select :enddate, :class=>"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :message %>
          <p class="help-block">
            Write a message to the Space Owner expressing your interest in the space. Explain why you would be a great fit for this space's synergy. Include any additional info or questions for the Owner.
          </p>
          <%= f.text_area :message , :class=>"form-control", :rows=>"7"%>
        </div>

        <div class="actions">
          <%= f.submit :class=>"btn btn-default" %>
        </div>
      <% end %>
    </div>
    
  </div>

  <% end %>

</main>

<% if @coworker == false %>
  <script>
    $(function(){
      setTimeout(function(){
          $(".star > img").unbind('mouseout mouseover click hover');
          $(".star").css("cursor", "default");
        },500) 
    })
  </script>
<% end %>