config/routes.rb
Rails.application.routes.draw do
  resources :leases do 
    member do
      put "approve", to: "leases#approve"
      put "disapprove", to: "leases#disapprove"
    end
  end

  resources :users, only: [:show, :edit, :update]
  resources :spaces do
    resources :leases
  end
  
  root to: 'pages#home'

#put 'users/:id' => 'users#update', :as => :id

  devise_for :users, :path => '', 
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up =>'signup'}

  get 'leases' => 'leases#index'
  get 'leases/:id' => 'leases#index'

  get 'listings' => 'pages#listings'
  get 'listings/search' => 'pages#listings'
  post 'listings/search' => 'pages#listings'

  get 'dashboard' => 'admin#dashboard'
  get 'dashboard/users' => 'admin#indexUsers'
  get 'dashboard/spaces' => 'admin#indexSpaces'

  get 'submission' => 'pages#submission'
  get 'spaces/new' => 'spaces#new'

  #get 'users/:id' => 'users#show'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/admin/makeAdmin' => 'admin#makeAdmin'
  post '/admin/makeAdmin' => 'admin#makeAdmin'

  get 'spaces/tagged/:tag', to: 'spaces#index', as: :tag



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_lease, only: [:show, :edit, :update, :destroy]

  # GET /leases
  # GET /leases.json
  def index
    @leases = Lease.all
  end

  # GET /leases/1
  # GET /leases/1.json
  def show
  end

  # GET /leases/new
  def new
    @lease = Lease.new
  end

  # GET /leases/1/edit
  def edit

  end

  # POST /leases
  # POST /leases.json
  def create
    @space = Space.find(params[:space_id])
    @lease = @space.leases.build(lease_params)
    @lease.user_id = current_user.id

    respond_to do |format|
      if @lease.save
        format.html { redirect_to @lease, notice: 'Lease was successfully created.' }
        format.json { render :show, status: :created, location: @lease }
      else
        format.html { render :new }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leases/1
  # PATCH/PUT /leases/1.json
  def update
    respond_to do |format|
      if @lease.update(lease_params)
        if @lease.accepted == true
          vac = @space.vacancies - 1
          @space.update_attribute(:vacancies, vac)
        end
        format.html { redirect_to @lease, notice: 'Lease was successfully updated.' }
        format.json { render :show, status: :ok, location: @lease }
      else
        format.html { render :edit }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    @lease = Lease.find(params[:id])
    @lease.update_attribute(:accepted, true)
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { lease_status: @lease.accepted} }
      format.js { render :layout => false }
    end
  end

  def disapprove
    @lease = Lease.find(params[:id])
    @lease.update_attribute(:accepted, false)
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { lease_status: @lease.accepted} }
      format.js { render :layout => false }
    end
  end

  # DELETE /leases/1
  # DELETE /leases/1.json
  def destroy
    @lease.destroy
    respond_to do |format|
      format.html { redirect_to leases_url, notice: 'Lease was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lease
      @lease = Lease.find(params[:id])
      @space = Space.find_by(id: @lease.space)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lease_params
      params.require(:lease).permit(:user, :space, :startdate, :enddate, :message, :accepted)
    end
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/views/leases/_form.html.erb
<%= form_for(@lease) do |f| %>
  <% if @lease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lease.errors.count, "error") %> prohibited this lease from being saved:</h2>

      <ul>
      <% @lease.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @lease.user == current_user %>
    <div class="field">
      <%= f.label :startdate %><br>
      <%= f.datetime_select :startdate %>
    </div>
    <div class="field">
      <%= f.label :enddate %><br>
      <%= f.datetime_select :enddate %>
    </div>
    <div class="field">
      <%= f.label :message %><br>
      <%= f.text_area :message %>
    </div>
    <div class="actions">
      <%= f.submit class:"btn btn-default top-margin bottom-margin" %>
    </div>
    <% else %>
      
    <div class="actions">
      <%= f.hidden_field :accepted, :value => "true" %>
      <%= f.submit "Approve Application", class:"btn btn-default top-margin" %>
    </div>
  <% end %>

  
<% end %>

app/views/leases/edit.html.erb
<main class="page">
	<h1>Editing lease</h1>

    <div class="panel panel-default">
      <div class="panel-heading star-col">
		<%= render 'form' %>

		<%= link_to 'Show', @lease, class:"btn btn-default top-margin" %>
		<%= link_to 'Back', leases_path, class:"btn btn-default top-margin" %>
		</div>
	</div>
</main>

app/views/leases/index.html.erb
<main class="page">


  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h3>Review Applicants</h3></div>
    <div class="panel-body">
      <p>Review the lease applications submitted for your spaces. </p>
    </div>

    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>View Applicant</th>
          <th>Space</th>
          <th>Startdate</th>
          <th>Enddate</th>
          <th>Message</th>
          <th>Accepted</th>
          <th id="rej" style="display: none">Reject</th>
          <th>View</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @leases.each do |lease| %>
          <tr>
            <% if lease.space != nil %>
              <% if lease.space.user == current_user %>
                <td>
                  <a href="/users/<%= lease.user.id %>">
                  <%= lease.user.name %>
                  </a>
                </td>

                <td>
                  <a href="/spaces/<%= lease.space.id %>">
                    <%= lease.space.name %>
                  </a>
                </td>
                <td><%= lease.startdate %></td>
                <td><%= lease.enddate %></td>
                <td><%= lease.message.gsub(/\n/, '<br/>').html_safe %></td>
                <% if not lease.accepted %>
                  <td id="tdWrap">
                    <p class="leaseStatus">
                      <%= link_to "Approve Lease", approve_lease_path(lease), method: :put, :remote => true, data: { type: :json }, class: "approveLease" %>
                    </p>
                  </td>
                <% else %>
                  <td id="stat"><%= lease.accepted %></td>
                <% end %>
                <td><%= link_to 'Show', lease %></td>
                <% end %> 
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h3>Your Applications</h3></div>
    <div class="panel-body">
      <p>These are applications you've submitted to others' spaces.</p>
    </div>

    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Owner</th>
          <th>Space</th>
          <th>Price</th>
          <th>Startdate</th>
          <th>Enddate</th>
          <th>Message</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @leases.each do |lease| %>
          <tr>
            <% if lease.space != nil %>
              <% if lease.user == current_user %>
                <td>
                  <a href="/users/<%= lease.space.user.id %>">
                    <%= lease.space.user.name %>
                  </a>
                </td>
                <td>
                  <a href="/spaces/<%= lease.space.id %>">
                    <%= lease.space.name %>
                  </a>
                </td>
                <td><%= lease.space.price %></td>
                <td><%= lease.startdate %></td>
                <td><%= lease.enddate %></td>
                <td><%= lease.message %></td>
                <td><%= lease.accepted %></td>
                <td><%= link_to 'Show', lease %></td>
                <td><%= link_to 'Edit', edit_lease_path(lease) %></td>
                <td><%= link_to 'Destroy', lease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</main>

app/views/leases/new.html.erb
<main class="page">
	<h1>New lease</h1>

	<%= render 'form' %>

	<%= link_to 'Back', leases_path %>
</main>

app/views/leases/show.html.erb
<main class="page">

  <div class="panel panel-default">
    <div class="panel-heading star-col">
      <p class="space-title top-margin">
        <a href="/spaces/<%= @lease.space.id %>">
          <%= @lease.space.name %>
        </a>
      </p>
    </div>
    <div class="col-md-12 panel panel-default">
      <div class="space-text-box col-md-6">
        <p>
          <strong>User:</strong>
          <a href="/users/<%= @lease.user.id %>"><%= @lease.user.name %></a>
        </p>
        <p>
          <strong>Owner:</strong>
          <%= @lease.space.user.name %>
        </p>

        <p>
          <strong>Startdate:</strong>
          <%= @lease.startdate %>
        </p>

        <p>
          <strong>Enddate:</strong>
          <%= @lease.enddate %>
        </p>

        <p>
          <strong>Accepted:</strong>
          <%= @lease.accepted %>
        </p>

        <%= link_to 'Edit', edit_lease_path(@lease), class:"btn btn-default" %>
        <%= link_to 'Back', leases_path, class:"btn btn-default" %>
      </div>
      <div class="space-text-box col-md-6">
        <p>
          <strong>Message:</strong>
          <%= @lease.message.gsub(/\n/, '<br/>').html_safe %>
        </p>
      </div>
    </div>
  </div>
</main>