config/routes.rb
Rails.application.routes.draw do
  resources :leases do 
    member do
      put "approve", to: "leases#approve"
      put "disapprove", to: "leases#disapprove"
    end
  end

  resources :users, only: [:show, :edit, :update]
  resources :spaces do
    resources :leases
  end
  
  root to: 'pages#home'

#put 'users/:id' => 'users#update', :as => :id

  devise_for :users, :path => '', 
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up =>'signup'}

  get 'leases' => 'leases#index'
  get 'leases/:id' => 'leases#index'

  get 'listings' => 'pages#listings'
  get 'listings/search' => 'pages#listings'
  post 'listings/search' => 'pages#listings'

  get 'dashboard' => 'admin#dashboard'
  get 'dashboard/users' => 'admin#indexUsers'
  get 'dashboard/spaces' => 'admin#indexSpaces'

  get 'submission' => 'pages#submission'
  get 'spaces/new' => 'spaces#new'

  #get 'users/:id' => 'users#show'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/admin/makeAdmin' => 'admin#makeAdmin'
  post '/admin/makeAdmin' => 'admin#makeAdmin'

  get 'spaces/tagged/:tag', to: 'spaces#index', as: :tag



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand cover-heading" href="/">SynergySpace</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= 'active' if current_page?(root_path) %>">
              <%= link_to "Listings",   '/' %>
            </li>
            <% if user_signed_in? %>
            <li><a href="/leases">Applications</a></li>
              <li><a href="/spaces/new">New Space</a></li>
              <li>
                <a href="/users/<%= current_user.id %>">Profile</a>
              </li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
              </li>
            <% else %>
              <li class="<%= 'active' if current_page?(new_user_session_path) %>">
                  <a id="login" href="/login">Login</a>
              </li>
            <% end %>
          </ul>
          <form class="navbar-form navbar-right" id="searchForm">
            <input type="text" class="form-control" placeholder="Search synergy tags" id="query" val="">
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_login.html.erb
<% provide(:title, 'Login') %>


<div class="iframe-popup">
  <h1>Login</h1>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true, :class => 'inputbox', :type =>'email', :placeholder =>'Enter your email', :title => 'Enter a valid email', :required => true  %><br />

  <%= f.label :password %><br />
  <%= f.password_field :password, autocomplete: "off",:class => 'inputbox', :placeholder =>'Enter your password', :title => 'Password must be 8 to 64 characters long', :minlength => '8', :maxlength => '64', :required => true, :pattern => '.{8,}' %><br />

  <% if devise_mapping.rememberable? -%>
  <%= f.check_box :remember_me %> <%= f.label :remember_me %>
  <% end -%>

      <div><%= f.submit "Log in" %></div>
    <% end %>
    <%= render "devise/shared/links" %>
</div>

app/views/layouts/_signup.html.erb
<% provide(:title, 'Sign up') %>

<h1 class="text-center">Sign up</h1>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { multipart: true }) do |f| %>
  <%= devise_error_messages! %>

<%= f.label :name %><br />
<%= f.text_field :name, autofocus: true, :class=>'inputbox', :pattern => '^[a-zA-Z0-9 _]*[a-zA-Z0-9][a-zA-Z0-9 _]*$', :placeholder =>'Letters only, no spaces', :title => 'Letters only|No Spaces|30 char max', :maxlength => '30', :required => true %><br />

  <%= f.label :occupation %><br />
  <%= f.text_field :occupation, autofocus: true, :class=>'inputbox', :pattern => '^[a-zA-Z0-9 _]*[a-zA-Z0-9][a-zA-Z0-9 _]*$', :placeholder =>'Letters only, no spaces', :title => 'Letters only|No Spaces|30 char max', :maxlength => '30'%><br />

<%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true, :class => 'inputbox', :type =>'email', :placeholder =>'Enter your email', :title => 'Enter a valid email', :required => true %><br />

  <%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
    <%= f.password_field :password, autocomplete: "off",:class => 'inputbox', :placeholder =>'Enter your password', :title => 'Password must be 8 to 64 characters long', :minlength => '8', :maxlength => '64', :required => true, :pattern => '.{8,}' %>

<%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off",:class => 'inputbox', :placeholder =>'Enter your password', :title => 'Password must be 8 to 64 characters long', :minlength => '8', :maxlength => '64', :required => true, :pattern => '.{8,}' %><br />

      Add Your <%= f.label :avatar %>:
      <%= f.file_field :avatar %>
<br />
  <div><%= f.submit "Sign up"%></div>
<br />

<% end %>
<%= render "devise/shared/links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SynergySpace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='//fonts.googleapis.com/css?family=Droid+Serif:700italic' rel='stylesheet' type='text/css'>

  <script type="text/javascript" src="//www.google.com/jsapi"></script>

  <%= favicon_link_tag 'favicon.ico' %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<body>

	<% if user_signed_in? %>
		<% if current_user.admin? %> 
			<%= render 'admin/header' %>
		<% else %>
			<%= render 'layouts/header' %>
		<% end %>
		<main class="page-container">
			<% if notice %>
			  <p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-danger"><%= alert %></p>
			<% end %>
			<%= yield %>
		</main>
	<% elsif not current_page?(root_path) %>
		<%= render 'layouts/header' %>
		<main class="page-container">
			<%= yield %>
		</main>
	<% else %>
		<%= yield %>
	<% end %>

	
	<footer>
		<p>SynergySpace by Blue Screen || About || 
			<a href="/spaces">Listings</a> || 
			<a href="/signup">Signup</a> || 
			<% if not user_signed_in? %><a href="/login">Login</a><% end %>
		</p>
	</footer>


</body>
</html>